#!/bin/bash
# ============================================================================
# HedgeX Candlestick Cron Setup
# ============================================================================
# Installs cron jobs for all timeframe fetchers.
# Each cron job calls historical_candle_fetcher.py for its respective timeframe.
#
# Usage:
#   chmod +x supabase/setup/cron_setup.sh
#   ./supabase/setup/cron_setup.sh
#
# Requirements:
#   - Python 3.8+
#   - pip install redis websocket-client
#   - Redis env vars set (REDIS_HOST, REDIS_PORT, REDIS_PASSWORD)
# ============================================================================

set -euo pipefail

# ── Detect project root ──────────────────────────────────────────────────────
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"
PYTHON_BIN="${PYTHON_BIN:-python3}"

# Verify python works
if ! command -v "$PYTHON_BIN" &>/dev/null; then
    echo "❌ Python not found at: $PYTHON_BIN"
    echo "   Set PYTHON_BIN env var to the correct python path"
    exit 1
fi

echo "📂 Project root: $PROJECT_ROOT"
echo "🐍 Python: $($PYTHON_BIN --version)"

# ── Prepare log directory ────────────────────────────────────────────────────
LOG_DIR="$PROJECT_ROOT/logs/candle_fetcher"
mkdir -p "$LOG_DIR"
echo "📋 Logs directory: $LOG_DIR"

# ── Base fetcher command ─────────────────────────────────────────────────────
# Export Redis credentials to cron environment
REDIS_HOST="${REDIS_HOST:-redismanager.redis.cache.windows.net}"
REDIS_PORT="${REDIS_PORT:-6380}"
REDIS_PASSWORD="${REDIS_PASSWORD:-}"

FETCH_CMD="cd $PROJECT_ROOT && REDIS_HOST=$REDIS_HOST REDIS_PORT=$REDIS_PORT REDIS_PASSWORD=$REDIS_PASSWORD $PYTHON_BIN backend/services/historical_candle_fetcher.py"

# ── Cron job definitions ─────────────────────────────────────────────────────
# Format: "cron_expression|timeframe_minutes|days_back|description"
declare -a CRON_JOBS=(
    "*/1  * * * *|1|1|1-minute candles"
    "*/5  * * * *|5|1|5-minute candles"
    "*/15 * * * *|15|2|15-minute candles"
    "0,30 * * * *|30|3|30-minute candles"
    "0    * * * *|60|5|1-hour candles"
    "0 */4 * * *|240|10|4-hour candles"
)

# ── Install cron jobs ────────────────────────────────────────────────────────
TMPFILE=$(mktemp)

# Preserve existing crontab (excluding our jobs)
crontab -l 2>/dev/null | grep -v "candle_fetcher\|historical_candle_fetcher" > "$TMPFILE" || true

echo "" >> "$TMPFILE"
echo "# ── HedgeX Candlestick Fetcher Jobs (auto-generated by cron_setup.sh) ──" >> "$TMPFILE"

for entry in "${CRON_JOBS[@]}"; do
    IFS='|' read -r cron_expr timeframe days description <<< "$entry"
    log_file="$LOG_DIR/${timeframe}min.log"
    full_cmd="$FETCH_CMD --timeframe $timeframe --days $days >> $log_file 2>&1 # candle_fetcher"
    echo "$cron_expr $full_cmd" >> "$TMPFILE"
    echo "  ✅ Added: $cron_expr → ${timeframe}min (${days} days, $description)"
done

echo "" >> "$TMPFILE"

# Install the new crontab
crontab "$TMPFILE"
rm -f "$TMPFILE"

echo ""
echo "✅ Cron jobs installed! Verify with: crontab -l"
echo ""
echo "📋 Log files:"
for entry in "${CRON_JOBS[@]}"; do
    IFS='|' read -r cron_expr timeframe days description <<< "$entry"
    echo "   ${timeframe}min → $LOG_DIR/${timeframe}min.log"
done

echo ""
echo "🎯 To test immediately, run:"
echo "   $PYTHON_BIN $PROJECT_ROOT/backend/services/historical_candle_fetcher.py --timeframe 5 --days 1"
